/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_androidgames_framework_JniUtils */

#ifndef _Included_com_badlogic_androidgames_framework_JniUtils
#define _Included_com_badlogic_androidgames_framework_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_androidgames_framework_JniUtils
 * Method:    log
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_androidgames_framework_JniUtils_log
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_badlogic_androidgames_framework_JniUtils
 * Method:    copy
 * Signature: (Ljava/nio/ByteBuffer;[FII)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_androidgames_framework_JniUtils_copy
  (JNIEnv *, jclass, jobject, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
